nmapui/models.py
from libnmap.parser import NmapParser, NmapParserException
from nmapui.celeryapp import celery_pipe
from bson.objectid import ObjectId
from nmapui import mongo
import hashlib


class Users(object):
    @classmethod
    def find(cls, **kwargs):
        _users = []
        _dbusers = mongo.db.users.find(kwargs)
        for _dbuser in _dbusers:
            _users.append(User(id=_dbuser['_id'],
                               username=_dbuser['username'],
                               password=_dbuser['password'],
                               email=_dbuser['email']))
        return _users

    @classmethod
    def get(cls, user_id):
        _user = None
        if isinstance(user_id, unicode):
            user_id = ObjectId(user_id)

        if isinstance(user_id, ObjectId):
            _dbuser = mongo.db.users.find_one({'_id': user_id})
            _user = User(id=_dbuser['_id'],
                         username=_dbuser['username'],
                         password=_dbuser['password'],
                         email=_dbuser['email'])
        return _user

    @classmethod
    def add(cls, username=None, email=None, password=None):
        rval = False
        if username is not None and email is not None and password is not None:
            mongo.db.users.insert({'username': username,
                                   'email': email,
                                   'password': password})
            rval = True
        return rval

class User:
    def __init__(self, id, username, email, password):
        self.id = id
        self.username = username
        self.password = password
        self.email = email

    def is_authenticated(self):
        return True
    
    def is_active(self):
        return True
    
    def is_anonymous(self):
      return False
    
    def get_id(self):
        return unicode(self.id)

    def credentials_valid(self, _password):
        return hashlib.sha256(_password).hexdigest() == self.password

    def __repr__(self):
        return "<User {0}>".format(self.username)


class NmapTask(object):
    @classmethod
    def find(cls, **kwargs):
        _reports = []
        _dbreports = mongo.db.reports.find(kwargs)
        for _dbreport in _dbreports:
            _nmap_task = celery_pipe.AsyncResult(_dbreport['task_id'])
            _reports.append(_nmap_task)
        return _reports

    @classmethod
    def get(cls, task_id):
        _report = None
        if isinstance(task_id, str) or isinstance(task_id, unicode):
            try:
                _resultdict = celery_pipe.AsyncResult(task_id).result
            except NmapParserException:
                pass
        return _resultdict

    @classmethod
    def get_report(cls, task_id):
        _report = None
        if isinstance(task_id, str) or isinstance(task_id, unicode):
            try:
                _resultdict = celery_pipe.AsyncResult(task_id).result
                _resultxml = _resultdict['report']
                _report = NmapParser.parse_fromstring(_resultxml)
            except NmapParserException:
                pass
        return _report

    @classmethod
    def add(cls, user_id=None, task_id=None):
        rval = False
        if user_id is not None and task_id is not None:
            mongo.db.reports.insert({'user_id': user_id, 'task_id': task_id})
            rval = True
        return rval

nmapui/__init__.py
__author__ = 'Ronald Bister'
__email__ =  'mini.pelle@gmail.com'
__license__ = 'CC-BY'
__version__ = '0.1'

from flask import Flask
from nmapui import config
from flask.ext.pymongo import PyMongo
from flask.ext.login import LoginManager
import datetime

app = Flask(__name__)
app.config.from_object(config)

mongo = PyMongo(app)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "ui.login"

from nmapui.views import ui
from nmapui.views import nmap
app.register_blueprint(ui.appmodule)
app.register_blueprint(nmap.appmodule)

def unix2datetime(unixstr):
    _rstr = ''
    try:
        _dtime = datetime.datetime.fromtimestamp(int(unixstr))
        _rstr = _dtime.strftime('%d/%m/%Y %H:%M:%S')
    except ValueError:
        _rstr = 'Unknown'
    return _rstr

app.jinja_env.filters['unix2datetime'] = unix2datetime

if __name__ == '__main__':
    app.run()

nmapui/views.py
import os
from nmapui import app, login_manager, mongo
from nmapui.models import Users, Reports
from nmapui.tasks import celery_nmap_scan
from flask import render_template, request, redirect, url_for, flash
from flask.ext.login import login_user, logout_user, login_required, current_user
from werkzeug import secure_filename
from bson.objectid import ObjectId

@app.route('/', methods=['GET', 'POST'])
def index():
    return redirect(url_for('login'))


@app.route('/nmap/')
@login_required
def nmap_index():
    return render_template('nmap_index.html')


@app.route('/nmap/scans/')
@login_required
def nmap_scan():
    return render_template('nmap_scans.html')


@app.route('/nmap/tasks', methods=['GET', 'POST'])
@login_required
def nmap_tasks():
    scantypes = [ "-sT", "-sT", "-sS", "-sA", "-sW", "-sM",
            "-sN", "-sF", "-sX", "-sU" ]

    if request.method == "POST":
        if 'targets' in request.form:
            targets = request.form["targets"]
        else:
            abort(401)
        options = ""
        scani = int(request.form['scantype']) if 'scantype' in request.form else 0
        if 'ports' in request.form and len(request.form['ports']):
            portlist = "-p " + request.form['ports']
        else:
            portlist = ''
        noping = '-P0' if 'noping' in request.form else ''
        osdetect = "-O" if 'os' in request.form else ''
        bannerdetect = "-sV" if 'banner' in request.form else ''
        options = "{0} {1} {2} {3} {4}".format(scantypes[scani],
                                                  portlist,
                                                  noping,
                                                  osdetect,
                                                  bannerdetect)
        _celery_task = celery_nmap_scan.delay(targets=str(targets),
                                              options=str(options))
        Reports.add(user_id=current_user.id, task_id=_celery_task.id)
        return redirect(url_for('nmap_reports'))
    return render_template('nmap_tasks.html')


@app.route('/nmap/reports/')
@login_required
def nmap_reports():
    reports = Reports.find()
    msg = 'Dumping reports'
    #    msg = "Error while trying to connect to data store"
    return render_template('nmap_reports.html', msg=msg, reports=reports)


@app.route('/nmap/compare/')
@login_required
def nmap_compare():
    return render_template('nmap_compare.html')


@app.route('/test/', methods=['GET', 'POST'])
#@login_required
def test():
    username = "{0}:{1} {2}".format(current_user.id, current_user.username, type(unicode(current_user.id)))
#    if request.method == 'POST':
#        username = request.args.get('username')
    return render_template('test.html', username=username)

@login_manager.user_loader
def load_user(user_id):
    return Users.get(user_id)

@app.route("/login", methods=["GET", "POST"])
def login():
    if (request.method == 'POST' and 'username' in request.form and
       'password' in request.form):
        username = request.form['username']
        password = request.form['password']
        app_users = Users.find(username=username)
        if len(app_users) != 1:
            app_user = None
            flash("login failed: check username and password")
        else:
            app_user = app_users[0]

        if app_user and app_user.credentials_valid(password):
            login_user(app_user)
            return redirect(request.args.get("next") or url_for("nmap_index"))
    return render_template("nmap_login.html")


@app.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

nmapui/views/nmap.py
from nmapui import app
from nmapui.models import NmapTask
from nmapui.tasks import celery_nmap_scan
from flask import Blueprint, render_template, request, redirect, url_for
from flask.ext.login import login_required, current_user
from celery.states import READY_STATES
import json

appmodule = Blueprint('nmap', __name__, url_prefix='/nmap')

@appmodule.route('/')
@login_required
def nmap_index():
    return render_template('nmap_index.html')


@appmodule.route('/scan')
@login_required
def nmap_scan():
    return render_template('nmap_scans.html')


@appmodule.route('/tasks', methods=['GET', 'POST'])
@login_required
def nmap_tasks():
    scantypes = [ "-sT", "-sT", "-sS", "-sA", "-sW", "-sM",
            "-sN", "-sF", "-sX", "-sU" ]

    if request.method == "POST":
        if 'targets' in request.form:
            targets = request.form["targets"]
        else:
            abort(401)

        options = ""
        scani = int(request.form['scantype']) if 'scantype' in request.form else 0
        if 'ports' in request.form and len(request.form['ports']):
            portlist = "-p " + request.form['ports']
        else:
            portlist = ''
        noping = '-P0' if 'noping' in request.form else ''
        osdetect = "-O" if 'os' in request.form else ''
        bannerdetect = "-sV" if 'banner' in request.form else ''
        options = "{0} {1} {2} {3} {4}".format(scantypes[scani],
                                                  portlist,
                                                  noping,
                                                  osdetect,
                                                  bannerdetect)
        _celery_task = celery_nmap_scan.delay(targets=str(targets),
                                              options=str(options))
        NmapTask.add(user_id=current_user.id, task_id=_celery_task.id)
        return redirect(url_for('nmap.nmap_tasks'))

    _nmap_tasks = NmapTask.find(user_id=current_user.id)
    return render_template('nmap_tasks.html', tasks=_nmap_tasks)

@appmodule.route('/jsontasks', methods=['GET', 'POST'])
@login_required
def nmap_tasks_json():
    _nmap_tasks = NmapTask.find(user_id=current_user.id)
    _jtarray = []
    for _ntask in _nmap_tasks:
        tdict = {'id': _ntask.id,
                 'status': _ntask.status,
                 'ready': 0}
        if _ntask.result and 'done' in _ntask.result:
            tdict.update({'progress': float(_ntask.result['done'])})
        elif _ntask.result and 'report' in _ntask.result:
            tdict.update({'progress': 100})
        else:
            tdict.update({'progress': 0})
        if _ntask.status in READY_STATES:
            tdict.update({'ready': 1})
        _jtarray.append(tdict)

    return json.dumps(_jtarray)

@appmodule.route('/report/<report_id>')
@login_required
def nmap_report(report_id):
    _report = None
    if report_id is not None:
        _report = NmapTask.get_report(task_id=report_id)
    return render_template('nmap_report.html', report=_report)


@appmodule.route('/compare')
@login_required
def nmap_compare():
    return render_template('nmap_compare.html')


@appmodule.route('/test', methods=['GET', 'POST'])
#@login_required
def test():
    username = "{0}:{1} {2}".format(current_user.id, current_user.username, type(unicode(current_user.id)))
#    if request.method == 'POST':
#        username = request.args.get('username')
    return render_template('test.html', username=username)

nmapui/views/ui.py
from nmapui import login_manager
from nmapui.models import Users
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask.ext.login import login_user, logout_user, login_required

appmodule = Blueprint('ui', __name__)

@appmodule.route('/', methods=['GET'])
def index():
    return redirect(url_for('ui.login'))

@login_manager.user_loader
def load_user(user_id):
    return Users.get(user_id)

@appmodule.route("/login", methods=["GET", "POST"])
def login():
    if (request.method == 'POST' and 'username' in request.form and
       'password' in request.form):
        app_user = None
        username = request.form['username']
        password = request.form['password']
        if 'username' in request.form and len(request.form['username']):
            app_users = Users.find(username=username)
            if len(app_users) != 1:
                flash("login failed: check username and password")
                app_user = None
            else:
                app_user = app_users[0]

        if app_user and app_user.credentials_valid(password):
            login_user(app_user)
            return redirect(request.args.get("next") or url_for("nmap.nmap_index"))
    return render_template("nmap_login.html")


@appmodule.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('ui.index'))

nmapui/templates/base.html
<!DOCTYPE html>
<html>
<head>
<title>{{ title }}</title>
<title>{% block title %}{% endblock %} Web Nmap</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap -->
<link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
<link href="/static/css/jquery-ui-1.10.3.custom.min.css" rel="stylesheet" media="screen">
</head>
<body>
    <div class="row-fluid">
        <div class="span2">
        <!--Sidebar content-->
            <ul class="nav nav-list">
                <li {% if request.endpoint == 'nmap_index' %}class="active"{% endif %}>
                    <a href="/nmap/"><i class="icon-home"></i> Home</a>
                </li>
                <li {% if request.endpoint == 'nmap_scan' %}class="active"{% endif %}>
                    <a href="/nmap/scan"><i class="icon-fire"></i> Scan</a>
                </li>
                <li {% if request.endpoint == 'nmap_tasks' %}class="active"{% endif %}>
                    <a href="/nmap/tasks"><i class="icon-book"></i> Tasks</a>
                </li>
                <li {% if request.endpoint == 'nmap_compare' %}class="active"{% endif %}>
                    <a href="/nmap/compare"><i class="icon-random"></i> Compare</a>
                </li>
                <li {% if request.endpoint == 'logout' %}class="active"{% endif %}>
                    <a href="/logout"><i class="icon-off"></i> Logout</a>
                </li>

            </ul>
        </div>
        <div class="span10">
        <!--Body content-->
            {% block body %}
            {% endblock %}
        </div>
    </div>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script type='text/javascript'>
    {% block javascript %}
    {% endblock %}
    </script>
</body>
</html>

nmapui/templates/base_external.html
<!DOCTYPE html>
<html>
<head>
<title>{{ title }}</title>
<title>{% block title %}{% endblock %} Web Nmap</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap -->
<link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
{% block head %}
{% endblock %}
</head>
<body>
    <!--Body content-->
    {% block body %}
    {% endblock %}
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

nmapui/templates/nmap_compare.html
{% extends "base.html" %}
{% block body %}
    <!--Body content-->
    <form>
    <fieldset>
        <legend>Compare nmap reports</legend>
    </fieldset>
    </form>
{% endblock %}

nmapui/templates/nmap_index.html
{% extends "base.html" %}
{% block body %}
    <!--Body content-->
    <h3>nmap web scanner</h3>
{% endblock %}

nmapui/templates/nmap_login.html
{% extends "base_external.html" %}
{% block head %}
    <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

    </style>
{% endblock %}
{% block body %}
<!--Body content-->
    <div class="row-fluid">
        <div class="span4 column">
        </div>
        <div class="span4 column">
            <form method="POST" action="/login" class="form-signin">
                <h3 class="text-left">Please Sign in</h3>
                <input type="text" id="inputUsername" name="username" placeholder="Username"/>
                <input type="password" id="inputPassword" name="password" placeholder="Password"/>
                <label class="checkbox">
                    <input type="checkbox" value="remember-me" name="remember-me"> Remember me
                </label>
                <button class="btn btn-large btn-primary" type="submit">Sign in</button>
            <p>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="alert alert-error">
                        {% for message in messages %}
                            {{message}}
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}
            </p>
            </form>
        </div>
        <div class="span4 column">
        </div>
    </div>
{% endblock %}

nmapui/templates/nmap_report.html
{% extends "base.html" %}
{% block body %}
    <!--Body content-->
    <form>
    <fieldset><legend>nmap scan result</legend>
    <div class="accordion" id="accordion2">
        <div class="accordion-group">
            <table class="table table-striped">
                <th>Host</th><th>Started</th><th>Ended</th><th>Host status</th><th>Open services</th><th>Details</th>
                {% for scanned_host in report.hosts %}
                <tr>
                    <td> {{ scanned_host.address }} </td>
                    <td> {{ scanned_host.starttime|unix2datetime }} </td>
                    <td> {{ scanned_host.endtime|unix2datetime }} </td>
                    <td> {{ scanned_host.status }} </td>
                    <td> {{ scanned_host.get_open_ports()|count }} </td>
                    <td>
                        <div class="accordion-heading">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#{{ scanned_host.id|replace('.', '') }}">Details</a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="6">
                        <div id="{{ scanned_host.id|replace('.', '') }}" class="accordion-body collapse">
                            <div class="accordion-inner">
                                <table class="table table-striped">
                                    <th>Service</th><th>Status</th><th>Banner</th>
                                    {% for scanned_service in scanned_host.services %}
                                    <tr>
                                        <td>{{ scanned_service.port }}/{{ scanned_service.protocol }}</td>
                                        <td>{{ scanned_service.state }}</td>
                                        <td>{{ scanned_service.banner }}</td>
                                    </tr>
                                    {% endfor %}
                                </table>
                                <br/>
                                {% if scanned_host.os_fingerprinted %}
                                Fingerprint: {{ scanned_host.os }}
                                {% endif %}
                                Uptime: {{ scanned_host.uptime }}
                            </div>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    </fieldset>
    </form>
{% endblock %}

nmapui/templates/nmap_scans.html
{% extends "base.html" %}
{% block body %}
<!--Body content-->
    <form method="POST" action="/nmap/tasks">
    <fieldset>
        <div>
            <legend>Online nmap scanner</legend>
            <label>Target:</label>
            <input id="input_target" name="targets" type="text" placeholder="127.0.0.1">
            <span class="help-block">specify the ip, subnet or domain you want to target</span>
            <label class="checkbox"><input type="checkbox" name="noping" value="noping">
            Do not ping target(s)
            </label>
        </div>
        <div class="accordion" id="accordion2">
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#nmapOptions">
                    More options
                    </a>
                </div>
                <div id="nmapOptions" class="accordion-body collapse">
                    <div class="accordion-inner">
                        <label>Scan techniques:</label>
                        <select name="scantype">
                            <option id="1" value="1">Connect Scan</option>
                            <option id="2" value="2">Syn Scan</option>
                            <option id="3" value="3">Ack Scan</option>
                            <option id="4" value="4">Window Scan</option>
                            <option id="5" value="5">Maimon Scan</option>
                            <option id="6" value="6">Null Scan</option>
                            <option id="7" value="7">Fin Scan</option>
                            <option id="8" value="8">Xmas Scan</option>
                            <option id="9" value="9">UDP Scan</option>
                        </select>
                        <label>Ports specification:</label><input type="text" name="ports" placeholder="22-1024">
                        <span class="help-block">Ex: "22" or "1-65535" or "U:53,111,137,T:21-25,80,139,8080,S:9"</span>
                        <label class="checkbox"><input type="checkbox" name="os" value="os_detection">
                        Enable OS detection
                        </label>
                        <label class="checkbox"><input type="checkbox" name="banner" value="banner_detection">
                        Enable banner grabbing
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Scan</button>
    </fieldset>
    </form>
{% endblock %}

nmapui/templates/nmap_tasks.html
{% extends "base.html" %}
{% block body %}
    <!--Body content-->
    <form>
    <fieldset>
        <legend>nmap scans status</legend>
        <table id="tasktable" class="table table-striped">
        <th>Tasks</th><th>Status</th><th>Progress</th><th>Details</th>
        {% for nmap_task in tasks %}
            <tr>
                <td>{{ nmap_task.id }}</td>
                <td id="{{ nmap_task.id }}" class="taskstatus">{{ nmap_task.status }}</td>
                <td><div id="{{ nmap_task.id }}" class="progressbar"></div></td>
                <td id="{{ nmap_task.id }}" class="detailslink">
                {% if nmap_task.result and 'report' in nmap_task.result %}
                    <a href="{{ url_for('nmap.nmap_report', report_id=nmap_task.id) }}">Details</a>
                {% else %}
                    Details
                {% endif %}
                </td>
            </tr>
        {% endfor %}
        </table>
    </fieldset>
    </form>
{% endblock %}
{% block javascript %}
    var interval_id = 0;
    var tasks_done = new Array();

    ajax_handler = function(){
        $.ajax({ url: "/nmap/jsontasks",
                 success: task_update_handler
        });
    }
    task_update_handler = function(jsontasks) {
            var tasklist = $.parseJSON(jsontasks);
            var all_done = true;
            $.each(tasklist, function(index, ntask){
                var pbarid = ntask.id + '.progressbar';
                var pstatusid = ntask.id + '.taskstatus';
                var plinkid = ntask.id + '.detailslink';
                var details_link = "<a href=\"/nmap/report/" + ntask.id + "\">Details</a>";
                if((ntask.ready == 1) && ($.inArray(ntask.id, tasks_done) == -1)){
                    $('#' + pbarid).progressbar({value: ntask.progress});
                    $('#' + pstatusid).text(ntask.status);
                    $('#' + plinkid).html(details_link);
                    tasks_done.push(ntask.id);
                    all_done = false;
                }
                else if($.inArray(ntask.id, tasks_done) == -1){
                    $('#' + pbarid).progressbar({value: ntask.progress});
                    $('#' + pstatusid).text(ntask.status);
                    all_done = false;
                }
            });
            if(all_done){
                clearInterval(interval_id);
            }
    }          

$(function () {
    $(".progressbar")
        .progressbar()
        .height(10)
        .width(70)
        .find('.ui-progressbar-value').css({
            "background": '#F20081'
        });
    ajax_handler();
    interval_id = setInterval(ajax_handler, 2000);
});
{% endblock %}

nmapui/templates/test.html
{% extends "base.html" %}
{% block body %}
    <!--Body content-->
    lol: {{ username }}
{% endblock %}

{% block javascript %}
{% endblock %}